[window]
opacity = 0.95 # Hacker transparency
padding = { x = 10, y = 10 }

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 12.0

[colors.primary]
background = '#1a1b26' # TokyoNight background
foreground = '#a9b1d6'
